$ErrorActionPreference = 'Stop'

# Generated by the choco-setup skill.
# Install-ChocolateyZipPackage auto-shims every .exe it unzips. Chocolatey removes
# those shims automatically on uninstall, and the unzipped tools dir is purged with
# the package — so no manual file removal is needed here. This script exists so the
# package has an explicit, auditable uninstall entry point; extend it if the install
# script creates state outside the tools directory (registry keys, %APPDATA%, etc.).

$packageName = 'genplaylist'

Write-Host "$packageName uninstalled. Shims and unpacked files are removed by Chocolatey."
