$ErrorActionPreference = 'Stop'

# Generated by the choco-setup skill.
# The chocolatey-publish.yml workflow rewrites the version in the URLs and the
# two checksum values from the release's checksums.txt at publish time.

$packageName    = 'genplaylist'
$url64          = 'https://github.com/punkscience/genplaylist/releases/download/v0.0.0/genplaylist_0.0.0_windows_amd64.zip'
$url64arm       = 'https://github.com/punkscience/genplaylist/releases/download/v0.0.0/genplaylist_0.0.0_windows_arm64.zip'
$checksum64     = 'REPLACE_WITH_AMD64_SHA256'
$checksum64arm  = 'REPLACE_WITH_ARM64_SHA256'
$checksumType   = 'sha256'

# Select arch from the environment (fast, no WMI dependency).
if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') {
    $url      = $url64arm
    $checksum = $checksum64arm
} else {
    $url      = $url64
    $checksum = $checksum64
}

$toolsDir = Split-Path -Parent $MyInvocation.MyCommand.Definition

$packageArgs = @{
    packageName    = $packageName
    unzipLocation  = $toolsDir
    url64bit       = $url
    checksum64     = $checksum
    checksumType64 = $checksumType
}

# Downloads, verifies the SHA256, unzips, and auto-shims any .exe onto PATH.
Install-ChocolateyZipPackage @packageArgs
